#include<stdio.h>
#include<stdlib.h>
#include"header.h"


 int Encrypt(char fname[]){
    /*The Encrypt function encrypts the file we want to encrypt by changing each and every characters ascii value by random number's and stores it in the temporary file "temp.txt" as it converts the characters the random numbers generated are stored in "code.txt" file for future decryption and then writes the characters from "temp.c" to the file we want to encrypt and later it deletes the "temp.txt" file.*/
     //Variable rand_num is used to store the randon number generated by printRandoms()
    FILE *fpts, *fptt, *fptu;//File data type variables
     int rand_num,ch,nav;
     

fpts=fopen(fname, "r");//Opening the file
if(fpts==NULL)//Checking if NULL value returned
{
    
    (void)   printf(" File does not exists or error in opening..!!");
    exit(EXIT_FAILURE);//Exit if opening the file was failure
}
fptt=fopen("temp.txt", "w");//Opening temp.txt file
if(fptt==NULL)//Checking if NULL value returned
{
    (void)  printf(" Error in creation of file temp.txt ..!!");
    (void)fclose(fpts);
    exit(EXIT_FAILURE);//Exit if opening the file was failure
}
fptu = fopen("code.txt", "r+");//Opening code.txt file
     while((nav=fgetc(fptu))!=EOF){
         
     }
   
while((ch=fgetc(fpts)) != EOF)
{
     rand_num = printRandoms(20,90);//Generating random numbers between 20 and 90
        ch=ch+rand_num;//Changing the ascii value of each character in the file wrt the random number generated
        (void) fputc(ch,fptt);//Writes the changed character to "temp.txt"
       (void)fprintf(fptu,"%d",rand_num);//Writes the integer value rand_num to "code.txt" file
}
    (void)fclose(fpts);//Closing the file[fname]
    (void)fclose(fptt);//Closing "temp.txt"
    fpts=fopen(fname, "w");//Opening the file[fname] in write mode
if(fpts==NULL)
{
   (void) printf(" File does not exists or error in opening..!!");
    exit(EXIT_FAILURE);
}
fptt=fopen("temp.txt", "r");//Opening temp.txt in write form
if(fptt==NULL)
{
    (void)printf("--------------------------\n");

   (void) printf("File does not exists or error in opening..!!");
    (void)printf("\n--------------------------");

    (void) fclose(fpts);
    exit(EXIT_FAILURE);
}
    
     while((ch=fgetc(fptt)) != EOF)
{
    
        (void)fputc(ch,fpts);//Writing character to the file[fname]
}

    (void)fclose(fpts);//Closing the file[fname]
    (void)fclose(fptt);//Closing the file "temp.txt"
    (void)fclose(fptu);//Closing the file "code.txt"
    (void)remove("temp.txt");//Deleting the file "temp.txt
    return(EXIT_SUCCESS);

}
