//###Safe file###//
//Secure C project by J Jeshwanth Reddy and Shaurya Singh


#include <stdio.h>
#include <stdlib.h>

static int printRandoms(int lower, int upper);//printRandoms prototype
static int Encrypt(void);
static int Decrypt(void);

static int Encrypt(void){
    /*The Encrypt function encrypts the file
     we want to encrypt by changing each and every characters ascii value by 
     random number's and stores it in the temporary file "temp.txt" as it converts
      the characters the random numbers generated are stored in "code.txt" file for future 
      decryption and then writes the characters from "temp.c" to the file we want to encrypt and
       later it deletes the "temp.txt" file.*/
    char fname[20];//Name of file we want to encrypt
    int rand_num,ch;// Variable rand_num is used to store the randon number generated by printRandoms()
    FILE *fpts, *fptt, *fptu;//File data type variables
    (void)  printf("\n\n Encrypt a text file \n");
    (void) printf("--------------------------\n");

(void) printf(" Input the name of file to encrypt : ");
(void) scanf("%s", fname);//Inputing the file name

fpts=fopen(fname, "r");//Opening the file
if(fpts==NULL)//Checking if NULL value returned
{
    
    (void)   printf(" File does not exists or error in opening..!!");
    exit(EXIT_FAILURE);//Exit if opening the file was failure
}
fptt=fopen("temp.txt", "w");//Opening temp.txt file
if(fptt==NULL)//Checking if NULL value returned
{
    (void)  printf(" Error in creation of file temp.txt ..!!");
    (void)fclose(fpts);
    exit(EXIT_FAILURE);//Exit if opening the file was failure
}
fptu = fopen("code.txt", "w");//Opening code.txt file
   
while(1)
{
    ch=fgetc(fpts);//Extracting a single character from fpts file
    if(ch==EOF)//Checking if we have reached the end and terminate if we have reached the end
    {
        break;
    }
    else
    {   rand_num = printRandoms(20,90);//Generating random numbers between 20 and 90
        ch=ch+rand_num;//Changing the ascii value of each character in the file wrt the random number generated
        (void) fputc(ch,fptt);//Writes the changed character to "temp.txt"
       (void)fprintf(fptu,"%d",rand_num);//Writes the integer value rand_num to "code.txt" file
    }
}
    (void)fclose(fpts);//Closing the file[fname]
    (void)fclose(fptt);//Closing "temp.txt"
    fpts=fopen(fname, "w");//Opening the file[fname] in write mode
if(fpts==NULL)
{
   (void) printf(" File does not exists or error in opening..!!");
    exit(EXIT_FAILURE);
}
fptt=fopen("temp.txt", "r");//Opening temp.txt in write form
if(fptt==NULL)
{
   (void) printf(" File does not exists or error in opening..!!");
    (void) fclose(fpts);
    exit(EXIT_FAILURE);
}
    
while(1)
{
    ch=fgetc(fptt);//Reading character from "temp.txt" file
    if(ch==EOF)
    {
        break;
    }
    else
    {
        (void)fputc(ch,fpts);//Writing character to the file[fname]
    }
}
(void) printf(" File %s successfully encrypted ..!!\n\n", fname);
    (void)fclose(fpts);//Closing the file[fname]
    (void)fclose(fptt);//Closing the file "temp.txt"
    (void)fclose(fptu);//Closing the file "code.txt"
    (void)remove("temp.txt");//Deleting the file "temp.txt
    return(0);

}

 static int Decrypt(void){
     /*The Decrypt function decrypt the file we want to decrypt by changing each and every characters ascii value by using the numbers in "code.txt" file and stores it in the temporary file "temp.txt" and then writes the characters from "temp.c" to the file we want to dencrypt and later it deletes the "temp.txt" file.*/
    int num,code_ch,ch;
     //num is used to store a number from the file "code.txt"
     //code_ch is used to store the ascii value of the character from the fname file
     //ch is used to store the next numer from "code.txt" file
    char  fname[20];//Name of the file we are going to decrypt
    FILE *fpts, *fptt, *fptu;
    
    (void)printf("\n\n Decrypt a text file :\n");
    (void)printf("--------------------------\n");
    
    (void)printf(" Input the name of file to decrypt : ");
    (void)scanf("%s",fname);//Input file name
    
    fpts=fopen(fname, "r");//Opend the fname file in read mode
    if(fpts==NULL)//Check if NULL is returned
    {
        (void)printf(" File does not exists or error in opening..!!");
        exit(EXIT_FAILURE);
    }
    fptt=fopen("temp.txt","w+");//Open the "temp.txt" in write and read mode
    if(fptt==NULL)
    {
        (void)printf(" File does not exist or error in opening..!!\\Its temp mofo");
        (void)fclose(fpts);
        exit(EXIT_FAILURE);
    }
    fptu = fopen("code.txt", "r");//Open the "code.txt" file read file
    while((num = fgetc(fptu)) != EOF)//This loop decrypts the contents of the fname file and stores it in the temporary file temp.txt
    {
        num = num - 48;//Convert character to ascii value
        num = num*10;//Multiply the number by 10
        ch = fgetc(fptu);//Get the next number from "code.txt"
        ch = ch - 48;//Convert character to ascii value
        ch = ch + num;//Add the two numbers to get the final number to decode the character
        code_ch = fgetc(fpts);//Get the encrypted character from fname file
        code_ch = code_ch - ch;//Decrypt the character
        (void)fputc(code_ch, fptt);//Write the decrypted character to "temp.txt" file
    }
     (void)fclose(fpts);
    (void)fclose(fptt);
    fpts = fopen(fname, "w+");//Open the fname file write and read mode
    fptt = fopen("temp.txt", "r+");//Open the "temp.txt" file read and write mode
    while((ch = fgetc(fptt)) != EOF)//Read character from "temp.txt"
    {
        (void)fputc(ch, fpts);//Write character to fname file
    }
    

    (void)printf(" The file %s decrypted successfully..!!\n\n",fname);
    (void)fclose(fpts);//Close fname file
    (void)fclose(fptt);//Close "temp.txt" file
    (void)remove("temp.txt");//Delete temp.txt
    return(0);
}

static int printRandoms(int lower, int upper)//printRandom function is a function that return random values between lower and upper values
{
        int num = (rand() % (upper - lower + 1)) + lower;
        return num;
}

//The main function starts from here

int main()
{
   
    
    int Input;
   (void) printf("Please Enter 1 to Encrypt File\n");
    (void) printf("Please Enter 2 to Decrypt File\n");
    (void) printf("Please Enter your option :- ");
    (void)scanf("%d",&Input);
    //Switch statement starts from here
    switch (Input) {
          
            //Case 1 starts from here [Encryption]
            
        case 1:
        {
            (void)Encrypt();
        }
            break;
            
            //Case 2 starts from [Decrypting]
            
        case 2:
        {
            (void)Decrypt();
        }
            break;
            
        default:
            (void)printf("Error !!");
            exit(EXIT_FAILURE);
            
    }
    return(EXIT_SUCCESS);
}
